//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAN_software.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAN_software.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN_software.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGridpg.
        /// </summary>
        public static string ContentGridpgPageTitle {
            get {
                return ResourceManager.GetString("ContentGridpgPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string CreateConnectButtonText {
            get {
                return ResourceManager.GetString("CreateConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string CreateNewFileButtonText {
            get {
                return ResourceManager.GetString("CreateNewFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent File.
        /// </summary>
        public static string CreateOpenFileButtonText {
            get {
                return ResourceManager.GetString("CreateOpenFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string CreateSaveFileButtonText {
            get {
                return ResourceManager.GetString("CreateSaveFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayCanGridPg.
        /// </summary>
        public static string DisplayCanGridPgPageTitle {
            get {
                return ResourceManager.GetString("DisplayCanGridPgPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeRibbonpg.
        /// </summary>
        public static string HomeRibbonpgPageTitle {
            get {
                return ResourceManager.GetString("HomeRibbonpgPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ListDetailspgListDescription {
            get {
                return ResourceManager.GetString("ListDetailspgListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetailspg.
        /// </summary>
        public static string ListDetailspgPageTitle {
            get {
                return ResourceManager.GetString("ListDetailspgPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PortText {
            get {
                return ResourceManager.GetString("PortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellPageRibbonBackstageTabSettingsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonBackstageTabSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Configuration.
        /// </summary>
        public static string ShellPageRibbonCANGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonCANGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ShellPageRibbonCANGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonCANGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Window.
        /// </summary>
        public static string ShellPageRibbonCANGroupCommon3Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonCANGroupCommon3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Window.
        /// </summary>
        public static string ShellPageRibbonCANGroupCommon4Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonCANGroupCommon4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Files.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ShellPageRibbonJ1939GroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonJ1939GroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ShellPageRibbonJ1939GroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonJ1939GroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J1939 Setting.
        /// </summary>
        public static string ShellPageRibbonJ1939GroupCommon3Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonJ1939GroupCommon3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Window.
        /// </summary>
        public static string ShellPageRibbonJ1939GroupCommon4Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonJ1939GroupCommon4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Window.
        /// </summary>
        public static string ShellPageRibbonJ1939GroupCommon5Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonJ1939GroupCommon5Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Configuration.
        /// </summary>
        public static string ShellPageRibbonLINGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonLINGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Window.
        /// </summary>
        public static string ShellPageRibbonLINGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonLINGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Window.
        /// </summary>
        public static string ShellPageRibbonLINGroupCommon3Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonLINGroupCommon3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN.
        /// </summary>
        public static string ShellPageRibbonTabCANHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabCANHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ShellPageRibbonTabHomeHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabHomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J1939.
        /// </summary>
        public static string ShellPageRibbonTabJ1939Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabJ1939Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIN.
        /// </summary>
        public static string ShellPageRibbonTabLINHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabLINHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ShellPageRibbonTabToolsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabToolsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Converter.
        /// </summary>
        public static string ShellPageRibbonToolsGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonToolsGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string ShellPageRibbonToolsGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonToolsGroupCommon2Header", resourceCulture);
            }
        }
    }
}
